function sigma = maxgar(sigmaBkg,sigmaInc,fi)
    Nk = [0.5;0.5;0];
    
    num = (1 / 3) .* fi .* (sigmaInc - sigmaBkg) .*...
          (sigmaBkg ./ (sigmaBkg + Nk(1) .* (sigmaInc - sigmaBkg)) +...
          sigmaBkg ./ (sigmaBkg + Nk(2) .* (sigmaInc - sigmaBkg)) +...
          sigmaBkg ./ (sigmaBkg + Nk(3) .* (sigmaInc - sigmaBkg)));
      
    den = 1 - ((1 / 3) .* fi .* (sigmaInc - sigmaBkg) .*...
          (Nk(1) ./ (sigmaBkg + Nk(1) .* (sigmaInc - sigmaBkg)) +...
          Nk(2) ./ (sigmaBkg + Nk(2) .* (sigmaInc - sigmaBkg)) +...
          Nk(3) ./ (sigmaBkg + Nk(3) .* (sigmaInc - sigmaBkg))));
      
    sigma = sigmaBkg + (num ./ den);
end